#!/bin/bash
curl -s http://repos.sensuapp.org/apt/pubkey.gpg | apt-key add -
echo "deb http://repos.sensuapp.org/apt sensu main" > /etc/apt/sources.list.d/sensu.list

apt-get update -qq
apt-get install -yqq git sensu

update-rc.d sensu-api defaults
